#pragma once

#define WINDOW_CLASS_NAME L"CASTLEvania"
#define MAIN_WINDOW_TITLE L"CASTLEvania"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 150

#define ID_TEX_SIMON 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20


const enum  SCREENSIZE
{
	WIDTH=520,
	HEIGHT=420
};

const enum ONSTAIRDIRECTION
{
	DEFAULT = -1,
	UPRIGHT,
	UPLEFT,
	DOWNRIGHT,
	DOWNLEFT,
};